// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmwupggiemotcrfpplgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtd3VwZ2dpZW1vdGNyZnBwbGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDI3OTQsImV4cCI6MjA2MDMxODc5NH0.n0yXtGCkF61yK_J-n51r99dSaa2hJm09aMZMoL2IqME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);